name: CI/CD Pipe

on:
  push:
    branches:
      - main
    tags:
      - '*'
jobs:
  build-image :
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0  # Fetch all history including tags
    
    - name: Set up Node.js
      if: success()
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install dependencies
      if: success()
      run: npm install

    - name: Build
      if: success()
      run: npm run build

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Build Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: maayysseem/landing-page:latest
