name: CI/CD Pipeline

on:
  push:
    tags: 
      - '*'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0  # Fetch all history including tags
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm install

    - name: Build
      run: npm run build

    - name: Get commit SHA
      id: get_sha
      run: echo "::set-output name=sha::$(git rev-parse --short=8 $GITHUB_SHA)"

    - name: Determine tag
      id: get_tag
      run: |
        TAG=$(git describe --tags --exact-match 2>/dev/null || echo "")
        if [ -z "$TAG" ]; then
          echo "No tags found, using commit SHA"
          TAG=${{ steps.get_sha.outputs.sha }}
          PUSH=false
        else
          echo "Tag found: $TAG"
          PUSH=true
        fi
        echo "::set-output name=tag::$TAG"
        echo "::set-output name=push::$PUSH"

    - name: Log in to Docker Hub
      if: steps.get_tag.outputs.push == 'true'
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Build Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: ${{ steps.get_tag.outputs.push }}
        tags: maayysseem/landing-page:${{ steps.get_tag.outputs.tag }}
