name: CI/CD Pipe

on:
  push:
    branches:
      - main
    tags:
      - '*'
jobs:
  build-image :
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0  # Fetch all history including tags
    
    - name: Set up Node.js
      if: success()
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install dependencies
      if: success()
      run: npm install

    - name: Build
      if: success()
      run: npm run build

    - name: Get commit SHA
      if: success()
      id: get_sha
      run: echo "::set-output name=sha::$(git rev-parse --short=8 $GITHUB_SHA)"

    - name: Determine tag
      if: success()
      run: |
          TAG=$(git describe --tags --exact-match 2>/dev/null || echo "")
          if [ -z "$TAG" ]; then
            echo "No tags found, using commit SHA"
            TAG=${{ steps.get_sha.outputs.sha }}
            PUSH=false
          else
            echo "Tag found: $TAG"
            PUSH=true
          fi
          echo "::set-output name=tag::$TAG"
          echo "::set-output name=push::$PUSH"

    - name: Build Docker image
      if: success()
      run: |
          if [ "${{ steps.get_tag.outputs.tag }}" == "" ]; then
            # If no tag, use commit SHA
            docker build -t maayysseem/landing-page:${{ steps.get_sha.outputs.sha }} .
          else
            # If tag exists, use the tag
            docker build -t maayysseem/landing-page:${{ steps.get_tag.outputs.tag }} .
          fi
  synchronize-backup :
   needs : build-image
   runs-on: ubuntu-latest
   steps:

    - name: Set up Git
      if: success()
      run: |
        git config --global user.name "maayysseem"
        git config --global user.email "karmaouimayssem@gmail.com"

    - name: Add SSH key
      if: success()
      uses: webfactory/ssh-agent@v0.5.4
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
        
    - name: Clone Backup Repository as Mirror
      run: |
        git clone --mirror git@github.com:mayssem-karmaoui/uni-backup-.git backup-mirror.git
        
    - name: Fetch Latest Changes from Main Repository
      if: success()
      run: |
        cd backup-mirror.git
        git remote add uni-landing-page git@github.com:mayssem-karmaoui/uni-landing-page.git
        git fetch uni-landing-page

    - name: Push to Backup Repository
      if: success()
      run: |
        cd backup-mirror.git
        git push --mirror git@github.com:mayssem-karmaoui/uni-backup-.git

  push-to-docker-hub :
    needs: build-image 
    runs-on: ubuntu-latest
    
    steps:
      - name: Log in to Docker Hub
        if: ${{ needs.build-image.outputs.push == 'true' }}
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Push Docker image
        if: ${{ needs.build-image.outputs.push == 'true' }}
        uses: docker/build-push-action@v4
        with:
         context: .
         push: true
         tags: maayysseem/landing-page:${{ steps.get_tag.outputs.tag }}


  
